= User Guide
Klaus UNGER <unger@spengergasse.at>
v0.1, 2018-01-25
:example-caption!:
:media: prepress
:icons: font

ifdef::backend-pdf[:imagesoutdir: ../../../build/asciidoc/{backend}/images]
ifdef::backend-pdf[:imagesdir: ../../../build/asciidoc/{backend}/images]

:toc:

== Abstract

This documents explains the basic options when writing your paper in http://asciidoc.org/[asciidoc] with the http://asciidoctor.org/[asciidoctor] tooling.

== Usage

Below you will find some instructions how to use this repository.

=== Introduction into writing with AsciiDoc(tor)

We'll begin with the definition of terms, just to clarify the inherent naming ambiguity.

AsciiDoc::
Describes the grammar of the text format for writing.

AsciiDoctor::
Is a (originally) ruby based tooling pipeline for processing *AsciiDoc* files.

=== How to build the PDF documents?

. In the `project directory`, open a terminal / command prompt
. Invoke the maven wrapper for your platform without any arguments
.. Unix: `./mvnw`
.. Windows: `.\mvnw.cmd`
. You will find the generated documents in `project-directory/target/asciidoc/pdf

<<<

== AsciiDoc Syntax crash course

=== Headers

[source,asciidoc]
----
= Header - Level 1

== Header - Level 2

=== Header - Level 3
----

=== Paragraphs

[source,asciidoc]
----
Writing a sentence will not define a paragraph.
A newline neither.

Without special indication, only an empty line will start a new paragraph.
Hence this source would lead to the following representation
----

[NOTE]
====
Writing a sentence will not define a paragraph.
A newline neither.

Without special indication, only an empty line will start a new paragraph.
Hence this source would lead to the following representation.
====

=== Lists

==== Numbered lists

[source,asciidoc]
----
. Is a list entry on the first level
.. Is a list entry on the second level
... Is a list entry on the third level
----

[NOTE]
====
. Is a list entry on the first level
.. Is a list entry on the second level
... Is a list entry on the third level
====

==== Unordered lists

[source,asciidoc]
----
* Is a list entry on the first level
** Is a list entry on the second level
*** Is a list entry on the third level
----

[NOTE]
====
* Is a list entry on the first level
** Is a list entry on the second level
*** Is a list entry on the third level
====

==== Mixed lists

[source,asciidoc]
----
. Is a list entry on the first level
** Is a list entry on the second level
... Is a list entry on the third level
----

[NOTE]
====
. Is a list entry on the first level
** Is a list entry on the second level
... Is a list entry on the third level
====

<<<

=== Tables

[source,asciidoc]
----
.Table Title
[cols="40,60", options="header"]
|===
|Header1
|Header2

|col 1, row 1
|col 2, row 1

|col 1, row 2
|col 2, row 2
|===
----

[NOTE]
====
.Table Title
[cols="40,60", options="header"]
|===
|header1
|header2

|col 1, row 1
|col 2, row 1

|col 1, row 2
|col 2, row 2
|===
====

=== Source listings

One can add source code samples with *embedded sources* and through *file inclusion*.
Following you find a sample for embedded sources.

[source,asciidoc]
....
[source,java]
----
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello world!"); // <1>
  }
}
----
....

[source,java]
----
public class Main {
  public static void main(String[] args) {
    System.out.println("Hello world!"); // <1>
  }
}
----

<1> Can be used as call-outs

<<<

=== UML Diagrams

One can add *UML diagrams* be embeddng a block with e.g. http://plantuml.com/[plantUML] syntax.

[source,asciidoc]
----
.Class diagram
[plantuml, "generated/plantuml-diagram", png]
....
 class BlockProcessor
 class DiagramBlock
 class DitaaBlock
 class PlantUmlBlock

 BlockProcessor <|-- DiagramBlock
 DiagramBlock <|-- DitaaBlock
 DiagramBlock <|-right- PlantUmlBlock
....
----

This will render the uml diagram as png and includes automatically the image.

.Class diagram
[plantuml, "generated/plantuml-diagram", png]
....
 class BlockProcessor
 class DiagramBlock
 class DitaaBlock
 class PlantUmlBlock

 BlockProcessor <|-- DiagramBlock
 DiagramBlock <|-- DitaaBlock
 DiagramBlock <|-right- PlantUmlBlock
....

<<<

=== AsciiArt (Ditaa) Diagrams

One can add basic block diagrams following the http://ditaa.sourceforge.net/[Ditaa] syntax.

[source, asciidoc]
----
.Basic ditaa block output
[ditaa, "generated/ditaa-diagram", png]
....
                    +-------------+
                    | Asciidoctor |-------+
                    |  Diagram    |       |
                    +-------------+       | PNG out
                        ^                 |
                        | ditaa in        |
                        |                 v
  +--------+   +--------+----+    /----------------\
  |        | --+ Asciidoctor +--> |                |
  |  Text  |   +-------------+    |Beautiful output|
  |Document|   |   !magic!   |    |                |
  |     {d}|   |             |    |                |
  +---+----+   +-------------+    \----------------/
      :                                   ^
      |          Lots of work             |
      +-----------------------------------+
....
----

This will render the diagram as png and includes automatically the image.

.Basic ditaa block output
[ditaa, "generated/ditaa-diagram", png]
....
                    +-------------+
                    | Asciidoctor |-------+
                    |  Diagram    |       |
                    +-------------+       | PNG out
                        ^                 |
                        | ditaa in        |
                        |                 v
  +--------+   +--------+----+    /----------------\
  |        | --+ Asciidoctor +--> |                |
  |  Text  |   +-------------+    |Beautiful output|
  |Document|   |   !magic!   |    |                |
  |     {d}|   |             |    |                |
  +---+----+   +-------------+    \----------------/
      :                                   ^
      |          Lots of work             |
      +-----------------------------------+
....

<<<

=== Includes

WARNING: Includes can be tricky!

[source, asciidoc]
----
\include::includes-sample.adoc[]
----

include::includes-sample.adoc[]
